# version: "3.8"

# services:
#   backend:
#     build: .
#     ports:
#       - "3000:3000"
#     depends_on:
#       - redis
#     environment:
#       REDIS_HOST: redis
#       REDIS_PORT: 6379
#     networks:
#       - app-network

#   redis:
#     image: redis:latest
#     ports:
#       - "6379:6379"
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge

version: "3.8"

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
